import numpy as np
import sounddevice as sd

from piper import PiperVoice, SynthesisConfig

voice = PiperVoice.load("en_US-lessac-medium.onnx")
config = SynthesisConfig()
lines = [
    "Welcome to the world of speech synthesis!",
    "This is a test of the Piper TTS system.",
    "Enjoy the natural-sounding voice generated by Piper."
]
for line in lines:
    for chunk in voice.synthesize(
        line,
        config
    ):
        audio = np.frombuffer(
            chunk.audio_int16_bytes,
            dtype=np.int16
        )

        sd.play(audio, samplerate=voice.config.sample_rate)
        sd.wait()
