import wave
import time
from piper import PiperVoice, SynthesisConfig
from piper.audio_playback import AudioPlayer

voice = PiperVoice.load("./en_US-lessac-medium.onnx")
# voice = PiperVoice.load("./fr_FR-gilles-low.onnx")
# voice = PiperVoice.load("./es_MX-claude-high.onnx")
# voice = PiperVoice.load("./es_MX-ald-medium.onnx")
syn_config = SynthesisConfig()
lines = [
    # "Welcome to the world of speech synthesis!",
    # "This is a test of the Piper TTS system.",
    # "Enjoy the natural-sounding voice generated by Piper.",
    # "The next text is in spanish:",
    "¡Bienvenidos al mundo de la síntesis de voz!",
    "¡Esto es una prueba del sistema de TTS Piper!",
    "¡Disfruta de la voz natural generada por Piper!"
]
silence = bytes([0] * voice.config.sample_rate)  # 1 second of silence (16-bit audio)

# with wave.open("test.wav", "wb") as wav_file:
#     voice.synthesize_wav("Welcome to the world of speech synthesis!", wav_file)
## Direct play not working
if AudioPlayer.is_available():
    with AudioPlayer(voice.config.sample_rate) as player:
        for line in lines:
            for i, audio_chunk in enumerate(voice.synthesize(line, syn_config)):
                print(f"Playing chunk {i} for line: {line}")
                player.play(audio_chunk.audio_int16_bytes)
                player.play(silence)
        time.sleep(5)
